<a href="https://colab.research.google.com/github/antoniosanch36/TareasCursoPhyton/blob/main/Tarea4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Un ciclo es un código que se repite varias veces hasta que se deja 
# de cumplir una condicion

# Iteracion: es el numero de veces que se ha repetido el ciclo

# Ciclo while

# Solicitar un numero par al usuario

Numero = int( input("Ingresa un numero par ") )

while Numero % 2 != 0:
  Numero = int( input("DIJE QUE INGRESARAS UN NUMERO PAR!!! ") )

print("El numero par es:", Numero)

Ingresa un numero par 5
DIJE QUE INGRESARAS UN NUMERO PAR!!! 2
El numero par es: 2


In [2]:
# Imprimiendo numeros del 1 al 5

i = 1
while i <= 5:
  print(i)
  i += 1

1
2
3
4
5


In [3]:
# Ciclo for 

# ciclo donde el numero de iteraciones normalmente es conocido
# la variable i toma un valor de la lista
# en cada iteracion

# Imprimir numeros del 1 al 5

for i in [1,2,3,4,5]:
  print(i)

1
2
3
4
5


In [4]:
# Funcion range crea un arreglo de numeros
# range(Inicio, Termina, incremento)
# range(num) el arreglo va desde cero hasta num - 1 de uno en uno

# Creando una lista con numeros del 0 al 10
y = range(11)
print( list(y) )

# Sumatoria de los elementos en x
x = [1,2,3,5,5]
Suma = 0

for i in x:
  Suma += i

print(Suma)

# Sumando de una forma diferente

Suma2 = 0
for i in range(5):
  Suma2 +=  x[i]

print(Suma2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
16
16


In [5]:

tamaño = len(x)

print("El tamaño de la lista es: ", tamaño)

for i in range(tamaño):
  if x[i] == 4:
    print("El numero 4 esta en la posicion",i)
    break



print("El numero de iteraciones fue: ", i + 1)

El tamaño de la lista es:  5
El numero de iteraciones fue:  5


Tarea

Multiplicar todos los elementos de una matriz ó lista de listas (de minimo 3x3) por un numero (puede ser el que sea menos 1 y 0) mediante ciclos y despues imprimir la nueva lista, pueden usar más de un ciclo o ciclos dentro de otros ciclos, pero mínimo deben de usar un ciclo

In [37]:
import numpy as np

I = np.zeros((10, 10)).astype(int)

for i in range(int(I.shape[0])):
    for j in range(int(I.shape[0])):
        if (i%2==0 and j%2==0):
            I[i,j] = i*j

print(I)

[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  4  0  8  0 12  0 16  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  8  0 16  0 24  0 32  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0 12  0 24  0 36  0 48  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0 16  0 32  0 48  0 64  0]
 [ 0  0  0  0  0  0  0  0  0  0]]


In [47]:
A = [ [1,2,3],[4,5,6],[7,8,9] ]
print(A)

for i in range(len(A)):
  for j in range(len(A[i])):
    A[i][j] = 3*(A[i][j])
    

  print(A)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[3, 6, 9], [12, 15, 18], [21, 24, 27]]
